name: Deploy Package to PyPi

on:
    release:
        types: [published]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    name: Deploy Package to PyPi

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
#          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Set Version
        run: echo "VERSION=$(sh .github/scripts/get_version.sh)" >> $GITHUB_ENV

      - name: Upgrade package installers
        run: python -m pip install --upgrade pip

      - name: Install Twine
        run: python -m pip install twine

      - name: Build package distribution
        run: python setup.py sdist --dist-dir ./dist

      - name: Upload package to PyPi
        run: twine upload -u __token__ -p "${{ secrets.PYPI_TOKEN }}" "./dist/pdfconduit-${VERSION}.tar.gz"