name: Style

on:
  push:

jobs:
  optimize-imports:
    runs-on: ${{ matrix.os }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.12" ]

    name: Optimize Imports & Reformat Code

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      #          cache: 'pip'

      - name: Upgrade package installers
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install code import optimizer dependencies
        run: python -m pip install -r requirements/imports.txt

      - name: Run Import Optimizers
        run: |
          isort .
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports .

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: OPTIMIZE imports (via isort & autoflake)
          status_options: '--untracked-files=no'
          file_pattern: '*.py'

      - name: Install code style fixer dependencies
        run: python -m pip install -r requirements/style.txt

      - name: Run Code Style Fixer
        run: |
          black pdfconduit
          black tests

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: REFORMAT code style (via black)
          status_options: '--untracked-files=no'
