name: Style

on:
  push:

jobs:
  optimize-imports:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.12" ]

    name: Optimize Imports & Reformat Code

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      #          cache: 'pip'

      - name: Upgrade package installers
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install code style & import optimizer dependencies
        run: |
          python -m pip install -r requirements/imports.txt
          python -m pip install -r requirements/style.txt

      - name: Run Import Optimizers & Code Style Fixer
        run: sh .github/scripts/optimize.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: REFORMAT code style & optimize imports (via black, isort & autoflake)
          status_options: '--untracked-files=no'
